config/routes.rb
SampleApp::Application.routes.draw do

  

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match "/help"   , :to =>'pages#help'
  match "/about"  , :to =>'pages#about'
  match "/contact", :to =>'pages#contact'
  match "/signup",  :to => 'users#new'
  match "/signin",  :to => 'sessions#new'
  match "/signout", :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
  attr_accessor :password	
  attr_accessible :email, :name, :password, :password_confirmation, :salt

  email_regex = /[\w\-.]+@[a-z\d\-.]+\.[a-z]+/
  validates :name, :presence => true,
  				   :length => {:maximum => 30 }

  validates :email, :presence => true,
  				    :format => {:with => email_regex},
  				    :uniqueness => {:case_sensitive => false}

  validates :password, :presence => true,
  					   :confirmation => true,
  					   :length => { :within => 8..20 }

  before_save :encrypt_password

  def has_password?(submitted_password)    
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email,password)
       user = find_by_email(email)
       return nil if user.nil?
       return user if user.has_password?(password)
  end

  private

  	def encrypt_password
      self.salt = make_salt
  		self.encrypted_password = encrypt(password)	  					   	
  	end	  	

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

  	def encrypt(password)
      secure_hash("#{salt}--#{password}")  					   
  	end			

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)       
    end	   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def help
  	@title = "Help"
  end

  def about
  	@title = "About"  	
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end

  def create

  	@title = "Sign up"
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to @user, :flash => { :success => "Welcome aboard!"}
  	else
  		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Return a title per page basis.
	def title
		base_title = "Ruby on rails tutorial"
		if @title.nil?
			base_title
	    else 
	    	"#{base_title} | #{@title}"
		end
	end	

	def logo
		image_tag("logo.png",:alt => "simple app", :class => "round")	
	end		
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
	def gravatar_img(user,options = {:size => 50})
		gravatar_image_tag(user.email,:class => 'gravatar',
									  :alt => user.name,
									  :gravatar => options
			)
	end
end

app/views/layouts/_header.html.erb
  <header>
    <%= link_to logo,root_path %>

    <nav class="round">
    	<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Sign In",'#' %></li>
    	</ul>

    </nav>
  </header>

app/views/layouts/_stylesheets.html.erb
	<script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<%= csrf_meta_tag %>
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<html>
<head>
	<title><%= title %></title>
<%= render 'layouts/stylesheets' %>
</head>
<body>
<div class="container">
<%= render "layouts/header"%>
<section class="round">
<% flash.each do  |key,value| %>
<div><%= value%></div>
<% end %>
<%= yield %>
</section>

  <footer>

    <nav class="round">
    	<ul>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "About", about_path%></li>
    	</ul>

    </nav>
  </footer>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is a help page</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>This is a help page</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Sign in",signup_path, :class => "signup_button round"%>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h3>
			<%= pluralize(@user.errors.count,"error") %>
			prohibited this user from being saved :
		</h3>
		<p>There were problems with the following fields:</p>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message%></li>
		<% end %>
	   </ul>
	</div>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@user) do |f|%>
<%= render '/shared/error_messages' %>
<div class="field">
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :email %><br>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %><br>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %><br>
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions">
	<%= f.submit "Signup" %>
</div>

<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
	<tr>
		<td class="main">
			<h2>
				<%= gravatar_img(@user) %>
				<%= @user.name %>
			</h2>
		</td>


		<td class="sidebar round">
			<strong>Nam</strong> <%= @user.name %> <br>
			<strong>URL</strong> <%= link_to users_path(@user.id), @user%>
		</td>	
	</tr>

</table>